apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-highload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-highload
  template:
    metadata:
      labels:
        app: go-highload
    spec:
      containers:
        - name: go-highload
          image: go-highload-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "redis-master:6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"